name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['24.11.0']

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ vars.PGUSER }}
          POSTGRES_PASSWORD: ${{ secrets.PGPASSWORD }}
          POSTGRES_DB: ${{ vars.PGDATABASE }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install migrate and test
        run: |
          npm ci
          npm run migrate up
          npm run test
        env:
          CI: true
          HOST: ${{ vars.HOST }}
          PORT: ${{ vars.PORT }}
          PGHOST: ${{ vars.PGHOST }}
          PGPORT: ${{ vars.PGPORT }}
          PGUSER: ${{ vars.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: ${{ vars.PGDATABASE }}
          PGSSLMODE: ${{ vars.PGSSLMODE }}
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
          REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
          ACCESS_TOKEN_AGE: ${{ vars.ACCESS_TOKEN_AGE }}